### ISSUE TITLE
Test example produces an empty VCF file

### ISSUE THREAD

**Issue by ialbert** [medvedevgroup/vargeno#4]
Running the test example from the documentation produces an empty VCF file:

```
vargeno index chr22.fa snp.vcf test_prefix
vargeno geno test_prefix reads.fq snp.vcf genotyped.vcf
```

the resulting `genotyped.vcf` file does not contain any variants:

`cat genotyped.vcf | tail -3`

produces:

```
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	DONOR

```

**Comment by bbsunchen** [comment]
I changed the test dataset, specifically reads sequences.
The old test dataset is expected to generate no meaningful result, which is confusing. 

With new test dataset, the expected output is [https://github.com/medvedevgroup/vargeno/blob/master/test/expected_output](https://github.com/medvedevgroup/vargeno/blob/master/test/expected_output)

**Comment by pashadag** [comment]
Hi Istvan, thanks for your feedback. Please let us know if the fix works for you.

**Comment by ialbert** [comment]
yes, looks good.  thanks for the fix.
